document.addEventListener('DOMContentLoaded',()=>{
 try{window.lucide?.createIcons?.();}catch{}
 let saved;try{saved=new Set(JSON.parse(localStorage.getItem('yellow-scripts:saved')||'[]'));}catch{saved=new Set();}
 const all=[...document.querySelectorAll('.script-card')];let category='',onlySaved=false;
 const search=document.querySelector('#search'),runtime=document.querySelector('#runtime');
 function sync(){document.querySelectorAll('[data-save]').forEach(b=>{const active=saved.has(Number(b.dataset.save));b.setAttribute('aria-pressed',String(active));b.title=active?'Убрать из избранного':'В избранное';});const count=document.querySelector('#saved-count');if(count)count.textContent=saved.size;}
 function filter(){let count=0;const query=(search?.value||'').toLowerCase().trim();all.forEach(c=>{const show=(!category||c.dataset.category===category)&&(!runtime.value||c.dataset.runtime===runtime.value)&&(!onlySaved||saved.has(Number(c.dataset.id)))&&query.split(/\s+/).every(term=>c.dataset.search.includes(term));c.hidden=!show;if(show)count++;});if(document.querySelector('#result-count'))document.querySelector('#result-count').textContent=count+' из 46';if(document.querySelector('#empty'))document.querySelector('#empty').hidden=count>0;}
 document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.save);saved.has(id)?saved.delete(id):saved.add(id);try{localStorage.setItem('yellow-scripts:saved',JSON.stringify([...saved]));}catch{}sync();if(all.length)filter();});
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{category=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(t=>t.classList.toggle('active',t===b));filter();});
 if(search)search.oninput=filter;if(runtime)runtime.onchange=filter;
 const savedButton=document.querySelector('#saved-only');if(savedButton)savedButton.onclick=()=>{onlySaved=!onlySaved;savedButton.setAttribute('aria-pressed',String(onlySaved));filter();};
 const clear=document.querySelector('#clear-filters');if(clear)clear.onclick=()=>{search.value='';runtime.value='';onlySaved=false;savedButton.setAttribute('aria-pressed','false');document.querySelector('[data-filter=""]').click();};
 sync();
 const surface=document.querySelector('.demo-surface');
 let frame,timeout;
 function launch(){if(!surface)return;clearTimeout(timeout);frame=document.createElement('iframe');frame.title=document.querySelector('h1').textContent;frame.sandbox='allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox';frame.allow='fullscreen';frame.style.height=surface.dataset.scroll==='true'?(surface.dataset.height||560)+'px':'240px';surface.replaceChildren(frame);const status=document.createElement('p');status.className='demo-loading';status.textContent='Загрузка примера…';surface.append(status);frame.onload=()=>{clearTimeout(timeout);try{if(!frame.contentDocument?.querySelector('body')||!frame.contentDocument.querySelector('meta[name="yellow-demo"]'))throw Error();status.remove();}catch{status.textContent='Не удалось загрузить пример. Нажмите «Перезапустить».';}};timeout=setTimeout(()=>status.textContent='Пример загружается дольше обычного. Можно повторить запуск.',12000);frame.src=surface.dataset.src+(document.querySelector('#code-variant')?'?variant='+document.querySelector('#code-variant').value:'');}
 const start=document.querySelector('#launch');if(start)start.onclick=launch;const restart=document.querySelector('#restart');if(restart)restart.onclick=launch;
 window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==frame?.contentWindow)return;const m=event.data;if(m?.type==='yellow-demo-height'&&surface.dataset.scroll!=='true'&&Number.isFinite(m.height))frame.style.height=Math.max(100,Math.min(4000,m.height))+'px';if(m?.type==='yellow-demo-variant')loadCode(m.variant);});
 document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==button.dataset.view);});
 let codeData;
 async function loadCode(variant){const host=document.querySelector('#code-files');if(!host)return;try{codeData??=await fetch(host.dataset.src).then(r=>{if(!r.ok)throw Error();return r.json();});const selected=codeData.variants?.find(v=>v.id===(variant||document.querySelector('#code-variant')?.value||codeData.variants[0].id));const files=selected?.files||codeData.files;host.replaceChildren();for(const file of files){const details=document.createElement('details');details.open=file.name==='index.html';const summary=document.createElement('summary');summary.textContent=file.name;const copy=document.createElement('button');copy.type='button';copy.className='copy-code';copy.textContent='Копировать';copy.onclick=async()=>{try{await navigator.clipboard.writeText(file.code);copy.textContent='Скопировано';}catch{copy.textContent='Выделите и скопируйте код';}};const pre=document.createElement('pre'),code=document.createElement('code');code.textContent=file.code;pre.append(code);details.append(summary,copy,pre);host.append(details);}const download=document.querySelector('#download');if(download)download.href=selected?.download||codeData.download;const picker=document.querySelector('#code-variant');if(picker&&variant)picker.value=variant;const separate=document.querySelector('[aria-label="Открыть пример отдельно"]');if(separate&&selected)separate.href=surface.dataset.src+'?variant='+selected.id;}catch{host.textContent='Не удалось загрузить код. Перезагрузите страницу или скачайте ZIP.';}}
 const picker=document.querySelector('#code-variant');if(picker)picker.onchange=()=>{loadCode(picker.value);if(frame)frame.src=surface.dataset.src+'?variant='+encodeURIComponent(picker.value);};
 loadCode();launch();
});
